baseURL: https://ffffffff0.github.io
title: "In Pursuit of Simplicity"
pagination:
  pagerSize: 5
theme: PaperMod

author:
  name: Hua Li
languageCode: en-us
rssLimit: 10
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
hasCJKLanguage: true # has chinese/japanese/korean ?

googleAnalytics: ""

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "HuaLi's Blog"
  description: "In Pursuit of Hubris"
  keywords: [Blog, Software, Life, Enginering]
  author: Li Hua
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowFullTextInRSS: true
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  hideAuthor: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  comments: true
  showtoc: true
  tocopen: false

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.svg"
    favicon32x32:  "/favicon-32x32.svg"
    apple_touch_icon:  "/apple-touch-icon.svg"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.svg
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: ExampleSite
    subtitle: "This is subtitle"
    imageUrl: "<img location>"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: >
      There is Li Hua's personal blog. \
      _-- **Li Hua**_

  analytics:
    google:
      SiteVerificationTag: ""

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/ffffffff0/ffffffff0.github.io/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  socialIcons:
    - name: github
      url: "https://github.com/ffffffff0"
defaultContentLanguageInSubdir: true
copyright: "See this site's source code [here](https://github.com/ffffffff0/ffffffff0.github.io), licensed under GPLv3 ·"
defaultContentLanguage: zh
languages:
  zh:
    title: "李华的博客"
    languageName: "中文"
    subtitle: "博客残本"
    contentDir: 'content/zh'
    weight: 2
    menu:
      main:
        - name: "归档"
          url: zh/archives/
          weight: 9
        - name: "搜索"
          url: zh/search/
          weight: 10
        - name: "标签"
          url: zh/tags/
          weight: 30
        - name: "关于"
          url: zh/about_me_zh/
          weight: 40
        - name: RSS
          url: "/zh/index.xml"
          weight: 50
        - identifier: series
          name: "系列 "
          url: /zh/categories/
          post: ' ▾'
          weight: 2
        - identifier: gain_and_loss
          parent: series
          name: "得失感悟"
          url: /zh/categories/得失感悟/
          weight: 1

markup:
  # https://github.com/adityatelange/hugo-PaperMod/issues/1386
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # style: modus-operandi # useless, need to set custom css
  goldmark:
    renderer:
      unsafe: true
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
